#!/usr/bin/env python3
"""Generate ros2_control YAML configuration from joint_limits.yaml and actuator_parameters.yaml.

Produces four files (effort + position variants):
  1. ros2_controllers.effort.yaml  — effort controller config with PID gains
  2. ros2_control.effort.urdf.xacro — effort command interface hardware snippet
  3. ros2_controllers.position.yaml — position controller config
  4. ros2_control.position.urdf.xacro — position command interface hardware snippet

Usage:
    python generate_ros2_control_config.py
    python generate_ros2_control_config.py --output-dir /path/to/config
    python generate_ros2_control_config.py --hardware-plugin gazebo
    python generate_ros2_control_config.py --hardware-plugin mock
"""

import argparse
import math
import re
from pathlib import Path

import yaml

CONFIGS_DIR = Path(__file__).resolve().parent.parent / "configs"

# Map suffixes found in joint names to actuator keys
SUFFIX_TO_ACTUATOR = {
    "X4": "X4-36",
    "X6": "X6-60",
    "X8": "X8-120",
}

# Hardware plugin presets
HARDWARE_PLUGINS = {
    "gazebo": "gz_ros2_control/GazeboSimSystem",
    "mock": "mock_components/GenericSystem",
    "ethercat": "ethercat_driver/EthercatSystem",
}

# Joint grouping by body section (order matters for readability)
SECTION_ORDER = ["body", "left_arm", "right_arm", "left_leg", "right_leg"]

SECTION_PATTERNS = {
    "body": ["waist"],
    "left_arm": ["left_shoulder", "left_elbow", "left_wrist"],
    "right_arm": ["right_shoulder", "right_elbow", "right_wrist"],
    "left_leg": ["left_hip", "left_knee", "left_ankle"],
    "right_leg": ["right_hip", "right_knee", "right_ankle"],
}


def classify_joint(joint_name: str) -> str:
    """Assign a joint to a body section."""
    for section, prefixes in SECTION_PATTERNS.items():
        for prefix in prefixes:
            if joint_name.startswith(prefix):
                return section
    return "body"


def detect_actuator(joint_name: str, default: str = "X8-120") -> str:
    """Extract actuator type from joint name suffix."""
    match = re.search(r"_(X\d+)$", joint_name)
    if match:
        suffix = match.group(1)
        return SUFFIX_TO_ACTUATOR.get(suffix, default)
    return default


def estimate_pid_gains(actuator_params: dict, joint_limits: dict) -> dict:
    """Estimate initial PID gains from actuator characteristics.

    Uses a conservative heuristic:
      - Kp ~ rated_torque / (range * 0.1)  (stiffness to correct 10% of range)
      - Kd ~ damping * 2  (slightly over-damped for stability)
      - Ki ~ Kp * 0.01  (small integral to eliminate steady-state error)
    """
    effort = joint_limits.get("effort", 10)
    lower = joint_limits.get("lower", -1.57)
    upper = joint_limits.get("upper", 1.57)
    damping = joint_limits.get("damping", 0.1)

    joint_range = abs(upper - lower) if abs(upper - lower) > 0.1 else 1.0

    kp = round(effort / (joint_range * 0.1), 1)
    kd = round(damping * 2, 3)
    ki = round(kp * 0.01, 3)

    return {"p": kp, "i": ki, "d": kd, "i_clamp": round(effort * 0.1, 2)}


def _build_controller_sections(sections: dict, all_joints: list,
                                joints: dict, actuators: dict,
                                default_actuator: str,
                                control_mode: str) -> str:
    """Generate ros2_controllers YAML for a given control_mode (effort or position)."""
    if control_mode == "effort":
        group_type = "effort_controllers/JointGroupEffortController"
    else:
        group_type = "joint_trajectory_controller/JointTrajectoryController"

    lines = []
    lines.append(f"# ros2_control {control_mode} controller configuration for Harambe humanoid")
    lines.append("# Generated by generate_ros2_control_config.py")
    lines.append("")
    lines.append("controller_manager:")
    lines.append("  ros__parameters:")
    lines.append("    update_rate: 100  # Hz")
    lines.append("")

    # Joint state broadcaster
    lines.append("    joint_state_broadcaster:")
    lines.append("      type: joint_state_broadcaster/JointStateBroadcaster")
    lines.append("      publish_rate: 50  # Hz")
    lines.append("")

    # IMU broadcaster
    lines.append("    imu_broadcaster:")
    lines.append("      type: imu_sensor_broadcaster/IMUSensorBroadcaster")
    lines.append("")

    # Per-section controllers
    for section in SECTION_ORDER:
        joint_list = sections[section]
        if not joint_list:
            continue
        ctrl_name = f"{section}_controller"
        lines.append(f"    {ctrl_name}:")
        lines.append(f"      type: {group_type}")
        lines.append("")

    # Whole-body controller
    lines.append("    whole_body_controller:")
    lines.append(f"      type: {group_type}")
    lines.append("")

    # --- Controller parameters ---
    lines.append("")

    # Joint state broadcaster params
    lines.append("joint_state_broadcaster:")
    lines.append("  ros__parameters:")
    lines.append("    joints:")
    for jn in all_joints:
        lines.append(f"      - {jn}")
    lines.append("    interfaces:")
    lines.append("      - position")
    lines.append("      - velocity")
    lines.append("      - effort")
    lines.append("")

    # IMU broadcaster params
    lines.append("imu_broadcaster:")
    lines.append("  ros__parameters:")
    lines.append("    sensor_name: imu_sensor")
    lines.append("    frame_id: imu_link")
    lines.append("")

    # Per-section controller params
    for section in SECTION_ORDER:
        joint_list = sections[section]
        if not joint_list:
            continue

        ctrl_name = f"{section}_controller"
        lines.append(f"{ctrl_name}:")
        lines.append("  ros__parameters:")
        lines.append("    joints:")
        for jn in joint_list:
            lines.append(f"      - {jn}")

        if control_mode == "effort":
            lines.append("    command_interfaces:")
            lines.append("      - effort")
            lines.append("    state_interfaces:")
            lines.append("      - position")
            lines.append("      - velocity")
            lines.append("")
            lines.append("    gains:")
            for jn in joint_list:
                actuator_key = detect_actuator(jn, default_actuator)
                actuator_params = actuators.get(actuator_key, {})
                pid = estimate_pid_gains(actuator_params, joints[jn])
                lines.append(f"      {jn}:")
                lines.append(f"        p: {pid['p']}")
                lines.append(f"        i: {pid['i']}")
                lines.append(f"        d: {pid['d']}")
                lines.append(f"        i_clamp: {pid['i_clamp']}")
            lines.append("")
        else:
            lines.append("    command_interfaces:")
            lines.append("      - position")
            lines.append("    state_interfaces:")
            lines.append("      - position")
            lines.append("      - velocity")
            lines.append("    allow_nonzero_velocity_at_trajectory_end: true")
            lines.append("    constraints:")
            lines.append("      stopped_velocity_tolerance: 0.01")
            lines.append("      goal_time: 0.0")
            lines.append("")

    # Whole-body controller
    lines.append("whole_body_controller:")
    lines.append("  ros__parameters:")
    lines.append("    joints:")
    for jn in all_joints:
        lines.append(f"      - {jn}")

    if control_mode == "effort":
        lines.append("    command_interfaces:")
        lines.append("      - effort")
        lines.append("    state_interfaces:")
        lines.append("      - position")
        lines.append("      - velocity")
        lines.append("")
        lines.append("    gains:")
        for jn in all_joints:
            actuator_key = detect_actuator(jn, default_actuator)
            actuator_params = actuators.get(actuator_key, {})
            pid = estimate_pid_gains(actuator_params, joints[jn])
            lines.append(f"      {jn}:")
            lines.append(f"        p: {pid['p']}")
            lines.append(f"        i: {pid['i']}")
            lines.append(f"        d: {pid['d']}")
            lines.append(f"        i_clamp: {pid['i_clamp']}")
        lines.append("")
    else:
        lines.append("    command_interfaces:")
        lines.append("      - position")
        lines.append("    state_interfaces:")
        lines.append("      - position")
        lines.append("      - velocity")
        lines.append("    allow_nonzero_velocity_at_trajectory_end: true")
        lines.append("    constraints:")
        lines.append("      stopped_velocity_tolerance: 0.01")
        lines.append("      goal_time: 0.0")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_controllers_yaml(joints: dict, actuators: dict,
                               default_actuator: str, control_mode: str) -> str:
    """Generate ros2_controllers YAML for the given control mode."""
    sections = {s: [] for s in SECTION_ORDER}
    for joint_name in joints:
        section = classify_joint(joint_name)
        sections[section].append(joint_name)

    all_joints = list(joints.keys())
    return _build_controller_sections(sections, all_joints, joints, actuators,
                                       default_actuator, control_mode)


def generate_ros2_control_xacro(joints: dict, actuators: dict,
                                 hardware_plugin: str, default_actuator: str,
                                 control_mode: str) -> str:
    """Generate ros2_control.urdf.xacro snippet."""
    lines = []
    lines.append('<?xml version="1.0"?>')
    lines.append('<robot xmlns:xacro="http://www.ros.org/wiki/xacro">')
    lines.append("")
    lines.append("  <ros2_control name=\"harambe_ros2_control\" type=\"system\">")
    lines.append("    <hardware>")
    lines.append(f"      <plugin>{hardware_plugin}</plugin>")
    lines.append("    </hardware>")

    for joint_name, limits in joints.items():
        actuator_key = detect_actuator(joint_name, default_actuator)
        params = actuators.get(actuator_key, {})

        lines.append("")
        lines.append(f"    <joint name=\"{joint_name}\">")

        if control_mode == "effort":
            lines.append("      <command_interface name=\"effort\">")
            lines.append(f"        <param name=\"min\">-{limits['effort']}</param>")
            lines.append(f"        <param name=\"max\">{limits['effort']}</param>")
            lines.append("      </command_interface>")
        else:
            lines.append("      <command_interface name=\"position\">")
            lines.append(f"        <param name=\"min\">{limits['lower']}</param>")
            lines.append(f"        <param name=\"max\">{limits['upper']}</param>")
            lines.append("      </command_interface>")

        lines.append("      <state_interface name=\"position\" />")
        lines.append("      <state_interface name=\"velocity\" />")
        lines.append("      <state_interface name=\"effort\" />")

        # Add actuator parameters as extra params
        if params:
            gear_ratio = params.get("gear_ratio", 1)
            inertia_kg_cm2 = params.get("inertia_Kg_cm2", 0)
            inertia_kg_m2 = inertia_kg_cm2 * 1e-4
            reflected_inertia = round(inertia_kg_m2 * gear_ratio ** 2, 6)
            torque_constant = params.get("module_torque_constant_Nm_per_A", 0)

            lines.append(f"      <!-- Actuator: {actuator_key} -->")
            lines.append(f"      <!-- gear_ratio: {gear_ratio} -->")
            lines.append(f"      <!-- reflected_rotor_inertia_kg_m2: {reflected_inertia} -->")
            lines.append(f"      <!-- torque_constant_Nm_per_A: {torque_constant} -->")

        lines.append("    </joint>")

    lines.append("")
    lines.append("  </ros2_control>")
    lines.append("")
    lines.append("  <!-- Gazebo gz_ros2_control plugin -->")
    lines.append("  <gazebo>")
    lines.append("    <plugin filename=\"gz_ros2_control-system\" name=\"gz_ros2_control::GazeboSimROS2ControlPlugin\">")
    lines.append(f"      <parameters>$(find harambe_description)/config/ros2_controllers.{control_mode}.yaml</parameters>")
    lines.append("      <update_rate>100</update_rate>  <!-- Hz, Gazebo plugin update rate -->")
    lines.append("    </plugin>")
    lines.append("  </gazebo>")
    lines.append("")
    lines.append("</robot>")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate ros2_control configuration from actuator and joint parameters"
    )
    parser.add_argument(
        "--joint-limits",
        default=str(CONFIGS_DIR / "joint_limits.yaml"),
        help="Path to joint_limits.yaml",
    )
    parser.add_argument(
        "--actuator-params",
        default=str(CONFIGS_DIR / "actuator_parameters.yaml"),
        help="Path to actuator_parameters.yaml",
    )
    parser.add_argument(
        "--output-dir",
        default=str(CONFIGS_DIR.parent.parent / "ldr-harambe-v0.3-procesed" / "config"),
        help="Output directory for generated files",
    )
    parser.add_argument(
        "--default-actuator",
        default="X8-120",
        help="Actuator for joints without a suffix (default: X8-120)",
    )
    parser.add_argument(
        "--hardware-plugin",
        default="gazebo",
        choices=list(HARDWARE_PLUGINS.keys()),
        help="Hardware plugin preset (default: gazebo)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output without writing files",
    )
    args = parser.parse_args()

    plugin = HARDWARE_PLUGINS[args.hardware_plugin]

    with open(args.joint_limits, "r") as f:
        limits_config = yaml.safe_load(f)
    joints = limits_config["joints"]

    with open(args.actuator_params, "r") as f:
        actuator_config = yaml.safe_load(f)
    actuators = actuator_config["actuators"]

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    for mode in ("effort", "position"):
        controllers_yaml = generate_controllers_yaml(joints, actuators,
                                                      args.default_actuator, mode)
        xacro_content = generate_ros2_control_xacro(joints, actuators, plugin,
                                                     args.default_actuator, mode)

        controllers_path = output_dir / f"ros2_controllers.{mode}.yaml"
        xacro_path = output_dir / f"ros2_control.{mode}.urdf.xacro"

        if args.dry_run:
            print(f"=== {controllers_path.name} ===")
            print(controllers_yaml)
            print(f"=== {xacro_path.name} ===")
            print(xacro_content)
            continue

        with open(controllers_path, "w") as f:
            f.write(controllers_yaml)
        print(f"Written: {controllers_path}")

        with open(xacro_path, "w") as f:
            f.write(xacro_content)
        print(f"Written: {xacro_path}")

    print(f"\nGenerated ros2_control config for {len(joints)} joints (effort + position)")
    print(f"Hardware plugin: {plugin}")


if __name__ == "__main__":
    main()
